# Generated by Django 4.0.5 on 2022-06-22 04:07

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_registro', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('doc_identidad_pac', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('domicilio', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('grado_instruccion', models.CharField(choices=[('Sin Grado', 'Sin Grado'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Tecnica', 'Tecnica'), ('Universitaria', 'Universitaria'), ('Master', 'Master'), ('Doctorado', 'Doctorado')], max_length=50)),
                ('tipo_seguro', models.CharField(choices=[('Sin seguro', 'Seguro'), ('Essalud', 'Essalud'), ('Ministerio de Salud', 'Ministerio de Salud'), ('EPS', 'EPS'), ('Privado', 'Privado'), ('Otro', 'Otro')], max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], default='Soltero', max_length=50, null=True)),
                ('grupo_etnico', models.CharField(blank=True, max_length=50, null=True)),
                ('acompaniante_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('companiante_parentezco', models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo(a)', 'Hijo(a)'), ('Abuelo(a)', 'Abuelo(a)'), ('Otro', 'Otro')], max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_registro', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('doc_identidad_trab', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('especialidad', models.CharField(choices=[('Nutricionista', 'Nutricionista')], default='Nutricionista', max_length=50)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nutri', models.TextField(blank=True, null=True)),
                ('req_ener', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('req_carboh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('req_prot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('req_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_patologia', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_dieta', models.CharField(blank=True, max_length=200, null=True)),
                ('r24_ener', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r24_carboh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r24_prot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r24_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r24_analisis', models.TextField(blank=True, null=True)),
                ('fc_analisis', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_registro', models.BooleanField(default=True)),
                ('file1', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Archivo 1')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriApp.paciente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('codigo_alimento', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_alimento', models.CharField(max_length=50)),
                ('energ', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('agua', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('prot_t', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grasa_t', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('carboh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fib', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('calc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fosf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('hier', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('b_carot', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vit_a', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tiam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ribo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('niac', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('vit_c', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('aci_fol', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('potas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('categoria_alimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nutriApp.categoria_alimento')),
            ],
        ),
    ]
