# Generated by Django 4.0.5 on 2022-06-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='companiante_parentezco',
            new_name='acompaniante_parentezco',
        ),
    ]
