# Generated by Django 4.0.5 on 2022-06-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'Trabajadores'},
        ),
    ]
