# Generated by Django 4.0.5 on 2022-06-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriApp', '0002_rename_companiante_parentezco_paciente_acompaniante_parentezco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='acompaniante_parentezco',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo(a)', 'Hijo(a)'), ('Esposo(a)', 'Esposo(a)'), ('Abuelo(a)', 'Abuelo(a)'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
